# Generated by Django 4.0.4 on 2022-05-25 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=5000)),
                ('label', models.CharField(max_length=2)),
            ],
        ),
    ]
